# Generated by Django 2.0.1 on 2018-03-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('types', models.CharField(blank=True, max_length=200, null=True)),
                ('place_id', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('reviews', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trip1',
            },
        ),
    ]
